name: docker-ci
on:
  push:
    branches: main
  pull_request:
    branches: dev
env:
  MAVEN_OPTS: "-Xms1024m -Xmx2048m -XX:+UseG1GC -XX:+UseStringDeduplication -noverify -Dmaven.artifact.threads=50 -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryhandler.count=5 -Dmaven.wagon.httpconnectionManager.ttlSeconds=240 -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -Dmaven.wagon.http.ssl.ignore.validity.dates=true"
  _JAVA_OPTIONS: "-Djava.io.tmpdir=/tmp/"
  COMPANY: "Leelatech LLC"
jobs:
  build:
    name: Build
    defaults:
      run:
        shell: bash
    runs-on:
      - Linux
      - X64
      - self-hosted
      - USA
 
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: ls    

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Nexus Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_URL}}
          username: ${{ secrets.DOCKER_USER}}
          password: ${{ secrets.DOCKER_PASS}}
      - name: Sets datetime tag
        run: echo "_DATE=$(date +%m%d%Y_%H%M)" >> $GITHUB_ENV
        
      - name: Shows datetime tag
        run: echo ${{ env._DATE }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          # platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY_URL}}/${{ github.event.repository.name }}:${{ env._DATE }}
            ${{ secrets.DOCKER_REGISTRY_URL}}/${{ github.event.repository.name }}:latest
          # ghcr.io/user/app:1.0.0

      - name: Showing image:tag
        run: echo ${{ secrets.DOCKER_REGISTRY_URL}}/${{ github.event.repository.name }}:${{ env._DATE }}

# ## Deploy Phase
#   deploy:
#     uses: leelatechllc/.github/.github/workflows/deploy.yaml@main
#     with:
#     #   argo-project: ace-api-dev
#     #   ecr-repository: honeycomb/ace-api
#     #   datadog-app-name: ace-api
#       #environment: prod
#       environment: ${GITHUB_REF##*/}
#       # environmentt: newman 
#     # secrets:
#     #   argo-username: ${{ secrets.ARGO_USER}}
#     #   argo-password: ${{ secrets.ARGO_PASSWORD }} 